apiVersion: v1
kind: ReplicationController
metadata:
  name: php-apache
spec:
  replicas: 1
  template:
    metadata:
      name: php-apache
      labels:
        app: php-apache
    sepc:
      containers:
      - name: php-apache
        image: gcr.io/google-containers/hpa-example
        resources:
          requests:
            cpu: 200m
        ports:
        - containerPort: 80